version: "3.8"
services:
    api:
        container_name: api
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: production
            MONGO_DB_URL: mongodb://mongodb:27017/discussion-fourm
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
            AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}

        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - "4005:4005"
    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
        ports:
            - "80:80"
    mongodb:
        image: mongo:latest
        volumes:
            - mongodb_data_container:/data/db

volumes:
    mongodb_data_container:
